# Generated by Django 5.0.4 on 2024-05-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_college_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='api.course'),
        ),
    ]
