# Generated by Django 5.0.4 on 2024-05-04 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_semester_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='college',
        ),
    ]
